CREATE TABLE IF NOT EXISTS `roles` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(50) NOT NULL UNIQUE, `description` VARCHAR(255), PRIMARY KEY (`id`)) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `kuts` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(100) NOT NULL, `description` TEXT, `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `role_id` INTEGER NOT NULL, `created_by` INTEGER, `email_verified_at` DATETIME, `verification_token` VARCHAR(255), `status` ENUM('active', 'inactive', 'pending') DEFAULT 'pending', `token` TEXT, `phone` VARCHAR(255), `address` VARCHAR(255), `is_active` TINYINT(1) DEFAULT true, `is_verified` TINYINT(1) DEFAULT false, `verification_expires` DATETIME, `last_login_at` DATETIME, `must_change_password` TINYINT(1) DEFAULT false, `totp_enabled` TINYINT(1) DEFAULT false, `totp_secret` VARCHAR(255), `telegram_chat_id` VARCHAR(255), `telegram_username` VARCHAR(255), `otp_telegram_chat_id` VARCHAR(255), `otp_telegram_username` VARCHAR(255), `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `seating_rows` (`id` INTEGER NOT NULL auto_increment , `row_num` INTEGER NOT NULL, `capacity` INTEGER NOT NULL DEFAULT 0, `assigned_taker_id` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`assigned_taker_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `user_profiles` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL UNIQUE, `kut_id` INTEGER, `first_name_kh` VARCHAR(100) NOT NULL, `last_name_kh` VARCHAR(100) NOT NULL, `first_name_en` VARCHAR(100), `last_name_en` VARCHAR(100), `phone_number` VARCHAR(20), `chhaya_number` VARCHAR(50) UNIQUE, `university_name` VARCHAR(255), `university_year` VARCHAR(50), `place_of_birth` VARCHAR(255), `date_of_birth` DATE, `ordained_date` DATE, `avatar_url` VARCHAR(255), `seat_number` VARCHAR(50), `bio` TEXT, `gender` VARCHAR(50), `from_wat` VARCHAR(255), `seating_row_id` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`kut_id`) REFERENCES `kuts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`seating_row_id`) REFERENCES `seating_rows` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;;

ALTER TABLE `user_profiles` ADD UNIQUE INDEX `user_profiles_seating_row_id_seat_number` (`seating_row_id`, `seat_number`);

CREATE TABLE IF NOT EXISTS `monk_surveys` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL UNIQUE, `surname_name` VARCHAR(255), `latin_name` VARCHAR(255), `nationality` VARCHAR(100) DEFAULT 'KHMER', `date_of_birth` DATE, `pob_province_id` VARCHAR(100), `pob_district_id` VARCHAR(100), `pob_commune_id` VARCHAR(100), `pob_village_id` VARCHAR(100), `preceptor_name` VARCHAR(255), `first_assistant_name` VARCHAR(255), `second_assistant_name` VARCHAR(255), `ordained_name` VARCHAR(255), `ordained_date` DATE, `ordination_wat` VARCHAR(255), `ordination_province_id` VARCHAR(100), `ordination_district_id` VARCHAR(100), `ordination_commune_id` VARCHAR(100), `current_wat` VARCHAR(255), `current_province_id` VARCHAR(100), `current_district_id` VARCHAR(100), `current_commune_id` VARCHAR(100), `phone_number` VARCHAR(50), `edu_level` VARCHAR(255), `edu_school` VARCHAR(255), `edu_specialty` VARCHAR(255), `edu_grade` VARCHAR(255), `current_job` VARCHAR(255), `kudi_number` VARCHAR(100), `father_name` VARCHAR(255), `father_occupation` VARCHAR(255), `mother_name` VARCHAR(255), `mother_occupation` VARCHAR(255), `parents_province_id` VARCHAR(100), `parents_district_id` VARCHAR(100), `parents_commune_id` VARCHAR(100), `parents_village_id` VARCHAR(100), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `student_surveys` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL UNIQUE, `surname_name` VARCHAR(255), `nationality` VARCHAR(100) DEFAULT 'KHMER', `date_of_birth` DATE, `pob_province_id` VARCHAR(100), `pob_district_id` VARCHAR(100), `pob_commune_id` VARCHAR(100), `pob_village_id` VARCHAR(100), `phone_number` VARCHAR(50), `id_card_number` VARCHAR(100), `other_number` VARCHAR(100), `edu_level` VARCHAR(255), `edu_school` VARCHAR(255), `edu_specialty` VARCHAR(255), `edu_grade` VARCHAR(255), `current_job` VARCHAR(255), `kudi_number` VARCHAR(100), `father_name` VARCHAR(255), `father_occupation` VARCHAR(255), `mother_name` VARCHAR(255), `mother_occupation` VARCHAR(255), `parents_province_id` VARCHAR(100), `parents_district_id` VARCHAR(100), `parents_commune_id` VARCHAR(100), `parents_village_id` VARCHAR(100), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `provinces` (`id` VARCHAR(100) , `name` VARCHAR(100) NOT NULL UNIQUE, `name_en` VARCHAR(100), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `districts` (`id` VARCHAR(100) , `province_id` VARCHAR(100) NOT NULL, `name` VARCHAR(100) NOT NULL, `name_en` VARCHAR(100), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`province_id`) REFERENCES `provinces` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `communes` (`id` VARCHAR(100) , `district_id` VARCHAR(100) NOT NULL, `name` VARCHAR(100) NOT NULL, `name_en` VARCHAR(100), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`district_id`) REFERENCES `districts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `addresses` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL, `address_type` ENUM('birth_place', 'current_place') DEFAULT 'birth_place', `province_id` VARCHAR(100), `district_id` VARCHAR(100), `commune_id` VARCHAR(100), `village_id` VARCHAR(100), `province` VARCHAR(255), `district` VARCHAR(255), `commune` VARCHAR(255), `village` VARCHAR(100), PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`province_id`) REFERENCES `provinces` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`district_id`) REFERENCES `districts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`commune_id`) REFERENCES `communes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `documents` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL, `document_type` ENUM('id_card', 'chhaya', 'student_card', 'other') NOT NULL, `file_path` VARCHAR(255) NOT NULL, `uploaded_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `otp_sessions` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL, `session_token` VARCHAR(255) NOT NULL, `otp_code` VARCHAR(10) NOT NULL, `expires_at` DATETIME NOT NULL, `used` TINYINT(1) DEFAULT false, `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `password_reset_tokens` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL, `token` VARCHAR(255) NOT NULL, `expires_at` DATETIME NOT NULL, `used` TINYINT(1) DEFAULT false, `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `refresh_tokens` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL, `token` VARCHAR(255) NOT NULL, `expires_at` DATETIME NOT NULL, `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `villages` (`id` VARCHAR(100) , `commune_id` VARCHAR(100) NOT NULL, `name` VARCHAR(100) NOT NULL, `name_en` VARCHAR(100), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`commune_id`) REFERENCES `communes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `attendance_rows` (`id` INTEGER NOT NULL auto_increment , `kut_id` INTEGER NOT NULL, `date` DATE NOT NULL, `taker_id` INTEGER NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`kut_id`) REFERENCES `kuts` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`taker_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `education_years` (`id` INTEGER NOT NULL auto_increment , `year` VARCHAR(20) NOT NULL UNIQUE, `is_active` TINYINT(1) DEFAULT false, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `retreat_events` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL, `start_date` DATE, `end_date` DATE, `is_active` TINYINT(1) DEFAULT false, `is_closed` TINYINT(1) DEFAULT false, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `attendances` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL, `row_id` INTEGER, `seating_row_id` INTEGER, `seat_number` VARCHAR(50), `kut_id` INTEGER, `date` DATE NOT NULL, `status` ENUM('present', 'absent', 'permission') NOT NULL DEFAULT 'present', `notes` TEXT, `fine_amount` DECIMAL(10,2) DEFAULT 0, `education_year_id` INTEGER, `retreat_event_id` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`row_id`) REFERENCES `attendance_rows` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`seating_row_id`) REFERENCES `seating_rows` (`id`), FOREIGN KEY (`kut_id`) REFERENCES `kuts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`education_year_id`) REFERENCES `education_years` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`retreat_event_id`) REFERENCES `retreat_events` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;;

ALTER TABLE `attendances` ADD UNIQUE INDEX `attendances_user_id_date` (`user_id`, `date`);

CREATE TABLE IF NOT EXISTS `retreat_registrations` (`id` INTEGER NOT NULL auto_increment , `retreat_event_id` INTEGER NOT NULL, `user_id` INTEGER NOT NULL, `seating_row_id` INTEGER, `seat_number` VARCHAR(50), `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`retreat_event_id`) REFERENCES `retreat_events` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`seating_row_id`) REFERENCES `seating_rows` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `universities` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(300) NOT NULL, `province` VARCHAR(100), `district` VARCHAR(100), `commune` VARCHAR(100), `village` VARCHAR(100), `website` VARCHAR(255), `email` VARCHAR(255), `tel` VARCHAR(100), `rector` VARCHAR(200), `establish_date` VARCHAR(20), `faculties` TEXT, `language` VARCHAR(50), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `payments` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL, `amount_paid` DECIMAL(10,2) NOT NULL, `paid_at` DATETIME, `education_year_id` INTEGER, `retreat_event_id` INTEGER, `collected_by` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`education_year_id`) REFERENCES `education_years` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`retreat_event_id`) REFERENCES `retreat_events` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`collected_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `fine_payments` (`id` INTEGER auto_increment , `user_id` INTEGER NOT NULL, `amount` DECIMAL(10,2) NOT NULL, `cleared_absents` INTEGER NOT NULL DEFAULT 3, `collected_by` INTEGER NOT NULL, `payment_date` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`collected_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `leave_requests` (`id` INTEGER auto_increment , `user_id` INTEGER NOT NULL, `retreat_event_id` INTEGER, `start_date` DATE NOT NULL, `end_date` DATE NOT NULL, `reason` TEXT NOT NULL, `status` ENUM('pending', 'pending_mekudi', 'pending_superadmin', 'approved', 'rejected') DEFAULT 'pending_mekudi', `approved_by` INTEGER, `image_url` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `ceremony_events` (`id` INTEGER auto_increment , `title` VARCHAR(255) NOT NULL, `description` TEXT, `event_date` DATE NOT NULL, `event_time` TIME, `created_by` INTEGER NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `event_kut_targets` (`id` INTEGER auto_increment , `event_id` INTEGER NOT NULL, `kut_id` INTEGER NOT NULL, `requested_monks_count` INTEGER NOT NULL DEFAULT 1, `status` ENUM('PENDING_MEKUDI', 'FULFILLED') DEFAULT 'PENDING_MEKUDI', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`event_id`) REFERENCES `ceremony_events` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`kut_id`) REFERENCES `kuts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;;

CREATE TABLE IF NOT EXISTS `event_participants` (`id` INTEGER auto_increment , `event_id` INTEGER NOT NULL, `user_id` INTEGER NOT NULL, `assigned_by` INTEGER, `status` VARCHAR(255) DEFAULT 'ASSIGNED', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`event_id`) REFERENCES `ceremony_events` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;;


INSERT INTO roles (id, name, description) VALUES 
(1, 'Superadmin', 'System Administrator'),
(2, 'Admin', 'Admin (Mekudi)'),
(3, 'Monk', 'Monk'),
(4, 'Student', 'Student'),
(5, 'AttendanceTaker', 'Attendance Taker');

INSERT INTO users (id, email, password, role_id, created_by, status, is_verified, email_verified_at, created_at, updated_at) VALUES 
(1, 'superadmin@pagoda.kh', '$2a$10$ditnAxgFDRlAxvrmFqDErOxBtSbFX4tfXfPT4bvWJT2NhiA0iM09q', 1, NULL, 'active', 1, NOW(), NOW(), NOW());
